### ISSUE TITLE
Unclear Dropdown Menu

### ISSUE THREAD

**Issue by physi3** [ollydevulder/thingreview#10]
When viewing on mobile or any screen thinner than 500px, the navigation bar becomes a dropdown menu. However, this is not clear and could o with some indication that this is a clickable button. 

![image](https://user-images.githubusercontent.com/45903919/97780313-d5649c00-1b7b-11eb-97a5-4984ffd781e4.png)

**Comment by physi3** [comment]
I believe some kind of logo would help with making it more clear that this is a drop-down menu such as this one. 
![Hamburger_icon svg](https://user-images.githubusercontent.com/45903919/97780354-0fce3900-1b7c-11eb-9a98-b85e41657436.png)

**Comment by ollydevulder** [comment]
I agree. This would be a useful and important feature!
Would you be willing to work on this enhancement and make a pull request to merge with `develop`?
Otherwise someone else will be assigned.
Thank you :sparkles:

**Comment by physi3** [comment]
I would be happy work on this in the coming days.

**Comment by ollydevulder** [comment]
I shall assign you then. Let me know if you would like any support :)

**Comment by ollydevulder** [comment]
I will commit my solution on the `develop` branch. Perhaps a follow-up issue should be opened in order to improve this enhancement?

**Comment by ollydevulder** [comment]
:arrow_up: here it is.
