### ISSUE TITLE
Using custom fonts for icons and icons on the navigation bar.

### ISSUE THREAD

**Issue by physi3** [ollydevulder/thingreview#16]
I think using a custom font would be a better solution for incorporating icons. The previous implementation downloaded all CSS from an independent online source.

Also, having icons consistent on the navigation bar would, arguably, improve the look of the website.

**Comment by physi3** [comment]
I would be happy to try implementing this enhancement.

**Comment by ollydevulder** [comment]
I will have a closer look at this at some point.
