### ISSUE TITLE
Least Reviewed Feature

### ISSUE THREAD

**Issue by physi3** [ollydevulder/thingreview#6]
I think an excellent feature to be added to the index page, would be a Least Reviewed thing link.
Thank you for your time.
Yours sincerely, Physi.

**Comment by ollydevulder** [comment]
This sounds like a good idea!
If you would like to contribute, feel free to make a pull request.

**Comment by ollydevulder** [comment]
Otherwise, I shall assign myself for this task.

**Comment by physi3** [comment]
I will work on this feature.
