### ISSUE TITLE
Most Recently Created Thing

### ISSUE THREAD

**Issue by physi3** [ollydevulder/thingreview#7]
I think an excellent feature to be added to the index page, would be a most recently created thing link.
Thank you for your time.
Yours sincerely, Physi.

**Comment by ollydevulder** [comment]
Again, I believe that this would be a useful addition to the app. Let me know if you plan on implementing this yourself, would like some help, or would like someone else to do it.
Thanks :)

**Comment by physi3** [comment]
I will work on this feature.

**Comment by physi3** [comment]
This feature does not work in it’s current state. To be implemented properly, reviews would have to be sorted by the created time.

**Comment by ollydevulder** [comment]
I have assigned myself to fix this feature.
